### ISSUE TITLE
Matrix testing on different python version still always uses python 3.12

### ISSUE THREAD

**Issue by pmrv** [pyiron/actions#123]
The unit tests seem to be run always with python 3.12, even if the unit test workflow says it's 3.9/3.10/whatever.
By accident I used a 3.12 syntax feature in [this PR](https://github.com/pyiron/pyiron_snippets/pull/20), which should (and does locally) make older pythons crash, but the unit test matrix runs fine.  So I stuck `import sys; print(sys.version)` into the tests and it does [report here](https://github.com/pyiron/pyiron_snippets/actions/runs/9905451401/job/27365040851?pr=20#step:4:981) that it runs 3.12 even though it's supposed to be the 3.9 test.

**Comment by pmrv** [comment]
I will revert the commits that added the print because I'd like the merge the corresponding PR soon, but I hope the link to the CI results stay alive.  If not it's easy enough to recreate.

**Comment by liamhuber** [comment]
Yikes, good catch. I immediately assumed it was a simple error on my part in failing to pass an input variable through the call chain, but in fact the code chain looks fine:

- Is input to [pyiron/actions/.github/workflows/push-pull.yml](https://github.com/pyiron/actions/blob/abb6ca6f9fb20d0bf8a29983361accea7c091769/.github/workflows/push-pull.yml#L124)
- Used in [the matrix for the unit-tests step](https://github.com/pyiron/actions/blob/abb6ca6f9fb20d0bf8a29983361accea7c091769/.github/workflows/push-pull.yml#L243)
- Passed to [pyiron/actions/unit-tests](https://github.com/pyiron/actions/blob/abb6ca6f9fb20d0bf8a29983361accea7c091769/.github/workflows/push-pull.yml#L270)
- Passed to [pyiron/actions/cached-miniforge](https://github.com/pyiron/actions/blob/abb6ca6f9fb20d0bf8a29983361accea7c091769/unit-tests/action.yml#L40)
- Passed to [conda-incubator/setup-miniconda](https://github.com/pyiron/actions/blob/abb6ca6f9fb20d0bf8a29983361accea7c091769/cached-miniforge/action.yml#L71)


Then I realized I could just look at the logs to confirm this, and it's the same thing: the 3.9 flag is successfully getting passed all the way through to `conda-incubator/setup-miniconda`:

<img width="1211" alt="Screen Shot 2024-07-12 at 09 20 27" src="https://github.com/user-attachments/assets/f273a377-953e-48cb-94ae-c659fa3c8077">

<img width="858" alt="Screen Shot 2024-07-12 at 09 22 44" src="https://github.com/user-attachments/assets/d7d2e23f-ed03-4c81-8860-2e171a8df7a2">

Indeed, the conda setup correctly shows 3.9 being requested:

<img width="703" alt="Screen Shot 2024-07-12 at 09 39 48" src="https://github.com/user-attachments/assets/32b9d76b-7a13-49f5-8adc-6b1052f7fce5">

And once we get the whole thing installed and run `conda list` for the logs, we _still_ see the correct version of python:

<img width="1067" alt="Screen Shot 2024-07-12 at 09 29 02" src="https://github.com/user-attachments/assets/a6c6ce02-8272-4fec-b917-a14006ff5f3e">

I then thought maybe we mess up the system variables? But the pyiron config business sets `CONDA: /home/runner/miniconda3`, which is exactly correct.

After that we just `coverage run`. The only remaining possibility I see for an issue with the workflow is that this command is somehow invoking the wrong version of python, but still has all the right packages? This is weird though as the env reports look fine here too:

<img width="993" alt="Screen Shot 2024-07-12 at 09 38 10" src="https://github.com/user-attachments/assets/2f30af6f-2c72-46c0-8821-7082c373ebbe">

> I will revert the commits that added the print because I'd like the merge the corresponding PR soon, but I hope the link to the CI results stay alive. If not it's easy enough to recreate.

Is there any possibility that somehow the reporting itself is the problem? I see you force-pushed in the linked PR so I can't see the source of the report. It seems extremely unlikely to me that the report is wrong, but given that the logs consistently show the right version throughout, I'm just very lost.

**Comment by jan-janssen** [comment]
It is very strange you have `python =3.9.19` and `python_abi =3.12` in the same environment, it should be `python_abi =3.9`. This seems to be related to the `mamba env update` command as I do not see the same issue on the repositories which directly set the `environment-file` in the `conda-incubator/setup-miniconda` action.

**Comment by liamhuber** [comment]
Very nice observation. So `coverage run` is really invoking the wrong executable.

Given that the python version kwarg is getting passed all the way to the conda incubator, it's a matter of seeing what other input we're passing that's creating a conflict (or, much less likely, there is a bug in the incubator action)

**Comment by liamhuber** [comment]
Also as far as I recall, we are writing our env file to the default location for the incubator setup, so even though it's not being set explicitly it should be getting passed in just fine. I'll double check that when I get to this though.

**Comment by liamhuber** [comment]
The problem appears a mixture of `mamba update` and having python versions explicitly in the env file. As you suggest, Jan, passing the env file directly to `setup-miniconda` solves this, but then we sacrifice caching.

The `mamba update` (and indeed the rest of the caching procedure) is exactly from [the conda-incubator docs on caching](https://github.com/conda-incubator/setup-miniconda?tab=readme-ov-file#caching-environments), which is most certainly what I followed when building this action. The interplay between the action argument for python versions and the env file used in the update specifying python versions is just a really unfortunate edge case that they aren't aware of/don't bother documenting.

I'm working on a PR (#124) which solves this by decomposing the caching into two steps so we can cache _and_ use the file directly at invocation of `setup-miniconda`. I'm quite confident it will work, but I still need to squash bugs in getting all the pathing working. I'll try to get to it tonight, but this might drag into tomorrow despite my promise to get a new release out by the end of the day.

**Comment by pmrv** [comment]
Thanks!  Like I said it's a not a time critical issue, but good that you figured it out so quickly.

**Comment by jan-janssen** [comment]
> The problem appears a mixture of `mamba update` and having python versions explicitly in the env file. As you suggest, Jan, passing the env file directly to `setup-miniconda` solves this, but then we sacrifice caching.

At least in my tests on the packages without `pyiron/actions` caching is no longer faster. Downloading the cache from Github takes longer than downloading the packages from anaconda.

**Comment by liamhuber** [comment]
> > The problem appears a mixture of `mamba update` and having python versions explicitly in the env file. As you suggest, Jan, passing the env file directly to `setup-miniconda` solves this, but then we sacrifice caching.
> 
> At least in my tests on the packages without `pyiron/actions` caching is no longer faster. Downloading the cache from Github takes longer than downloading the packages from anaconda.

My [recent experience](https://github.com/pyiron/actions/pull/124#issuecomment-2245856260) is that for very simple envs (the `pyiron_snippets` unit test env), loading the cache is indeed slightly slower than doing everything from scratch (35s vs 30s), but for a "complex" environment (`pyiron_base` + `dask`, neither with version pins) uncaching is significantly faster (27s vs 1m8s). Qualitatively, the gains on more complex setups seem worth risking the minor hit to performance for things that are already fast. Further, although my tests were N=1 and not scientific at all, un-caching seems pretty consistent -- so if you look at `pyiron_atomistics` where the mamba setup step is taking ~1.5m, we might be able to see some real gains. 

<img width="1211" alt="Screen Shot 2024-07-23 at 10 48 53" src="https://github.com/user-attachments/assets/d46797e2-9b03-478f-aa8b-dad9b2ae0984">

**Comment by liamhuber** [comment]
The speedup between writing and reading the cache is [significant for `pyiron_workflow`](https://github.com/pyiron/pyiron_workflow/pull/384): Ubuntu about 1.5m -> 0.75m, windows from 5m -> 2m. OSX was waiting too long in the queue so I don't know the speedup.
