### ISSUE TITLE
Be extra rigorous about using conda-forge

### ISSUE THREAD

**Issue by liamhuber** [pyiron/actions#127]
Due to anaconda license terms. `pyiron/actions/cached-miniforge` uses miniforge and strictly uses the conda-forge channel. I'll anyhow update the defaults for these args so we are explicitly requesting the `miniforge-channels` and `miiniforge-channel-priority` from our end rather than relying on the `setup-miniconda` defaults being favourable (although it seems unlikely they'll change these).

**Comment by liamhuber** [comment]
This is a non-issue, because we already expose the underlying arguments (in case you want to set them yourself), we _already_ override `conda-incubator/setup-miniconda` kwargs with our own kwargs in `cached-miniconda`, and these are exactly the "safe" ones that are both what we want and the current `setup-miniconda` defaults.

**Comment by liamhuber** [comment]
Nope, it looks like the `mamba update` call still eventually falls back to include `defaults`! 

<img width="897" alt="Screen Shot 2024-08-26 at 10 44 31" src="https://github.com/user-attachments/assets/7667c8fe-640d-40d9-9ea3-8b509d5c1f71">

**Comment by liamhuber** [comment]
Hmm, except the latest `cached-miniforge` never explicitly calls `mamba update` -- now it's _always_ `setup-miniconda`, so there's a possibility this is actually an upstream issue with `setup-miniconda` not following through...

**Comment by liamhuber** [comment]
Indeed, this is a known issue on [conda-incubator/setup-miniconda]() and even a known gotcha on []().

One solution is to specify `nodefaults` right in your env-file....

```
channels:
- conda-forge
- nodefaults
dependencies:
...
```

But this is still sub-optimal IMO.

**Comment by jan-janssen** [comment]
An alternative option, is to create your own `.condarc` using:
```
echo -e "auto_update_conda: False\nauto_activate_base: True\nnotify_outdated_conda: False\nchangeps1: False\npkgs_dirs:\n  - /home/runner/conda_pkgs_dir\nchannels:\n  - conda-forge\nalways_yes: True\nsolver: libmamba" > .condarc
```
then you can include it in the action using:
```
condarc-file: .condarc
```
I tested this for the `notebooks` test in https://github.com/pyiron/pyiron_atomistics/pull/1545

**Comment by liamhuber** [comment]
👍 I find this preferable to having to specify `channels: nodefaults` in each env file. It's still ugly compared to specifying the channel right in the `setup-miniconda` action and actually having it read that, so I'm working on a patch for the root action there.

**Comment by liamhuber** [comment]
The key thing in your solution is `channels:\n  - conda-forge`, as then the channels field is not initially empty and thus conda doesn't pre-populate it with `defaults`. It's possible you can then trim down the rest of the RC file and have `setup-miniconda` populate the rest, but I don't know what the interaction is between a provided RC file and the action arguments.

**Comment by liamhuber** [comment]
I [opened a PR](https://github.com/conda-incubator/setup-miniconda/pull/364) to fix it upstream.
