### ISSUE TITLE
Break apart tests

### ISSUE THREAD

**Issue by liamhuber** [pyiron/actions#16]
Right now unit tests, coverage, and codacy all get done at once and benchmark tests are separate, both on push or pull to main, while integration tests happen on labeling. There are two downsides:
- If coverage drops, the main branch gets a red X because of the "on push" call
- I'm not sure that coverage catches the benefits of benchmark and integration tests, which is a shame.

It would be nice to pull out codacy and coverage from the unittests matrix altogether, and run them on a different trigger (at least with a pull-only trigger, maybe with on-label). It is worth checking if benchmark and integration tests should be done before coverage too. Maybe we should relabel the "integration" tag to something like "tests" tag to represent that we're running the *full* test suite there.

**Comment by liamhuber** [comment]
Will removing coverage and codacy from push to main break the badges?

**Comment by jan-janssen** [comment]
> Will removing coverage and codacy from push to main break the badges?

You are right, I did not think about this part. Maybe we could run the coverage periodically every 24 hours? Then the coverage would be up to date and the tests on the last commit would still show a positive checkmark.

**Comment by jan-janssen** [comment]
I have an example for a periodic task https://github.com/pyiron/pyiron-statistics/blob/main/.github/workflows/statistic.yml

**Comment by jan-janssen** [comment]
> It would be nice to pull out codacy and coverage from the unittests matrix altogether

We had the coverage as separate action before:
https://github.com/pyiron/pyiron_gpl/blob/master/.github/workflows/coverage.yml

**Comment by jan-janssen** [comment]
> * I'm not sure that coverage catches the benefits of benchmark and integration tests, which is a shame.

It does not, in general counting the coverage of subprocesses is a bit more difficult. In particular as during the benchmark/ integration tests we install pyiron rather than executing it from the working directory. But maybe it makes sense to look at this again when we separate the calculation of the coverage to a separate GitHub action.

**Comment by liamhuber** [comment]
> You are right, I did not think about this part. Maybe we could run the coverage periodically every 24 hours? Then the coverage would be up to date and the tests on the last commit would still show a positive checkmark.

Yeah, this is fine by me. I already use the CodeQL re-usable workflow inside a cron job [over on ironflow under `weekly.yml`](https://github.com/pyiron/ironflow/blob/main/.github/workflows/weekly.yml), I think we could do something similar with a `daily.yml` workflow.

I think this leaves us open to edge cases where someone merges a PR that drops coverage without first applying the "tests" (or whatever we call it) tag to it, then two consecutive cron jobs wind up seeing this drop and we get our red X on the main branch. Personally I don't think that's a deal-breaker and am happy to go ahead with the cron plan.

**Comment by liamhuber** [comment]
> > * I'm not sure that coverage catches the benefits of benchmark and integration tests, which is a shame.
> 
> It does not, in general counting the coverage of subprocesses is a bit more difficult. In particular as during the benchmark/ integration tests we install pyiron rather than executing it from the working directory. But maybe it makes sense to look at this again when we separate the calculation of the coverage to a separate GitHub action.

I have to confess I didn't look carefully at how the other repos did it. ATM I treat unit, benchmark, and integration tests very equitably; in all cases `pyiron/actions/cached-mamba` is used to build an env and then  pip-install the repo. After that the only differences are where we point the unittests module. In the actual unit tests that we run on the matrix I propose to point this only at `tests/unit`; for the coverage workflow I propose to point this at `tests/` (`tests/benchmark, tests/integration, tests/unit`). I *think* this will then collect _all_ the tests together in a single process.
