### ISSUE TITLE
Which secrets can be organization wide?

### ISSUE THREAD

**Issue by liamhuber** [pyiron/actions#2]
The actions are secret-free and reusable anywhere, but the workflows here are tailored for pyiron module repositories. I think some of the secrets we have can be moved from repo secrets to organization secrets, such that when we set up a new *pyiron* repo that uses these workflows the repo creator needs to worry about adding as few secrets as possible.

* [x] Figure out which tokens are tied to a generic login and which to a particular repo
* [x] Add generic tokens to organization secrets

**Comment by jan-janssen** [comment]
For the organizational level I see `DEPENDABOT_WORKFLOW_TOKEN` and `PYPI_PASSWORD` while the `CODACY_PROJECT_TOKEN` is repository specific. Which again raises the question how much we use codacy.

**Comment by liamhuber** [comment]
- Codacy can be organization wide. ["Account API tokens are defined at the Codacy user account level. Each account API token authorizes access to the same organizations, repositories, and operations as the roles and permissions of the owner of the account."](https://docs.codacy.com/codacy-api/api-tokens/)
- PyPi *can* but isn't necessarily organization wide. ["You can create a token for an entire PyPI account, in which case, the token will work for all projects associated with that account. Alternatively, you can limit a token's scope to a specific project."](https://pypi.org/help/#apitoken) I logged in to check, and our current scope is "all projects", so this one can be an org secret too.
- Our `DEPENDABOT_WORKFLOW_TOKEN` seems only to be used in the `Update Depndabot PR` workflow, where it gets passed to `actions/checkout` and `ad-m/github-push-action`. As far as I can tell, both of these can instead just use the `github.token` (which they do by default, so there is no need to provide *anything*). @jan-janssen, am I missing something, or can we just get rid of this token? 

The rest of our infrastructure just relies on the github token

> For the organizational level I see DEPENDABOT_WORKFLOW_TOKEN and PYPI_PASSWORD while the CODACY_PROJECT_TOKEN is repository specific. Which again raises the question how much we use codacy.

Ah, good to see you! I was just about to post. Per the research above, as far as I can tell PYPI and CODACY are already global (but re-stated in each repo atm), and DEPENDABOT is not necessary(?)

**Comment by jan-janssen** [comment]
> * Our `DEPENDABOT_WORKFLOW_TOKEN` seems only to be used in the `Update Depndabot PR` workflow, where it gets passed to `actions/checkout` and `ad-m/github-push-action`. As far as I can tell, both of these can instead just use the `github.token` (which they do by default, so there is no need to provide _anything_). @jan-janssen, am I missing something, or can we just get rid of this token?

If I understand @niklassiemer correctly then we need the separate `DEPENDABOT_WORKFLOW_TOKEN` so that the changes trigger a new iteration of the tests - for example for `format black`. This does not work with the default `github.token`.

**Comment by liamhuber** [comment]
> If I understand @niklassiemer correctly then we need the separate DEPENDABOT_WORKFLOW_TOKEN so that the changes trigger a new iteration of the tests - for example for format black. This does not work with the default github.token.

Ok, fair. I won't get rid of it unless Niklas contradicts that statement. But in that case it can still be an organization secret.

@jan-janssen, unless you have any other concerns I'll go ahead and copy `DEPENDABOT_WORKFLOW_TOKEN`, `PYPI_PASSWORD`, and `CODACY_PROJECT_TOKEN` over to organization secrets from the org admin panel. From then on I expect all pyrion org repos to be able to run the workflows here without specifying any secrets first!

**Comment by jan-janssen** [comment]
> @jan-janssen, unless you have any other concerns I'll go ahead and copy `DEPENDABOT_WORKFLOW_TOKEN`, `PYPI_PASSWORD`, and `CODACY_PROJECT_TOKEN` over to organization secrets from the org admin panel. From then on I expect all pyrion org repos to be able to run the workflows here without specifying any secrets first!

Sounds good to me

**Comment by liamhuber** [comment]
@jan-janssen, I'm afraid I'll need you to take care of the Codacy token:
- Codacy allows account-wide API tokens ([docs](https://docs.codacy.com/codacy-api/api-tokens/)
- Codacy requires github login
- Github pyiron runner login has 2FA -- this is where you come in, I presume!

**Comment by jan-janssen** [comment]
@liamhuber I created the token and posted it in the pyiron administrative group.

**Comment by liamhuber** [comment]
@jan-janssen, I seem to have switched from "owner" to "member" of the pyiron organization and no longer have access to the organization settings tab. Did you remove me? I'm ok with that, I just want to make sure I follow what's happened. Then please either add the codacy token to an organization wide secret or add me back as owner/admin and I'll take care of it.

**Comment by jan-janssen** [comment]
> Did you remove me? 

Yes, I did. I guess there are still not yet really clear rules who should have access to those permissions. My current idea is to limit it to the people who have permanent positions at MPIE.

**Comment by liamhuber** [comment]
> > Did you remove me?
> 
> Yes, I did. I guess there are still not yet really clear rules who should have access to those permissions. My current idea is to limit it to the people who have permanent positions at MPIE.

@jan-janssen, yep, I agree the new setup is preferable unless and until we get a policy written down somewhere. The downside is for you though, as now you have to be the one to add the `CODACY_PROJECT_TOKEN` to our organization-wide secrets 😉
