### ISSUE TITLE
Why is tests/unit fixed for push-pull-main ? Could it be a variable? 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/actions#32]

**Comment by liamhuber** [comment]
It is currently the pattern in ironflow and not in base, atomistics, etc. I would like to see those other repos updated to this pattern. IMO it's ugly to clutter our main directory with "tests", "test_benchmarks", _and_ "test_integration" (as is the case in, eg, atomistics). So let's tuck them all into a single tests folder and clean things up.

**Comment by jan-janssen** [comment]
For me these are two steps at the same time. While I see the advantage of having the tests all in one folder, I think that combining these changes with the migration to GitHub actions is what makes it hard for @srmnitc and @mbruns91 to apply the Github actions to other repositories. So my suggestion would be to specify the test directory as variable and then I am fine with setting the default to `tests/unit` and `tests/benchmark`.

**Comment by liamhuber** [comment]
Two-stepping it is a good call. I'm open to making the directories variables.

Alternatively, the steps could be (1) move the directories in the other repos and change *their* tests accordingly, (2) apply pyiron/actions without changes.

I'm ok with either.

**Comment by jan-janssen** [comment]
I prefer the first solution, as we have not seen a lot of adoption of the `actions` for any pyiron repositories so far, we have to simplify the process first. Still by already setting the default to the new directory structure, those who want to follow the steps the other way around can still do so.
