### ISSUE TITLE
Update Windows an Mac OS X tests to Python 3.11

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/actions#50]
I noticed that currently the tests on windows and Mac OS X are executed on Python 3.10 rather than 3.11. Is there a specific reason why these are not yet updated?

**Comment by liamhuber** [comment]
Not a serious one, no; In my head 3.10 is the "main" supported version since that's what's running on CMTI. I have no real objection to switching the "main" version over to 3.11, although I would like for the OSX, Windows, build-notebooks, and build-docs to all use the same version to keep it "main".

**Comment by jan-janssen** [comment]
> Not a serious one, no; In my head 3.10 is the "main" supported version since that's what's running on CMTI.  I have no real objection to switching the "main" version over to 3.11, although I would like for the OSX, Windows, build-notebooks, and build-docs to all use the same version to keep it "main".

The only limitation I see with Python 3.11 is the lack of support for machine learning frameworks like `pytorch`, for this reason we run the Linux systems with Python 3.9, 3.10 and 3.11 . But for users who want to test pyiron on their local computer I would always recommend to use Python 3.11. 

Python 3.11 is the current Python version https://www.python.org/downloads/ . It still receives bug fixes while the main development is happening on Python 3.12 and all older versions like 3.10, 3.9 and 3.8 only receive security updates. 

Based on this I find it dangerous that the pyiron `main` Python version is not the current Python `main` version.
