### ISSUE TITLE
Dependabot update workflow might use wrong files?!

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/actions#55]
While the positions of the env and mapping file are fixed here 
https://github.com/pyiron/actions/blob/a4901bd626cd03a72ae7b699e2bc6b7d31c1b89b/.support/update_environment.py#L111-L112

They seem to be different for changed depandabot PR titles if I look at 
https://github.com/pyiron/actions/blob/a4901bd626cd03a72ae7b699e2bc6b7d31c1b89b/.support/update_environment.py#L74-L98

**Comment by liamhuber** [comment]
Yyyyyep. I think we got away with it because all of the PRs have been in "bump" format for so long so the error in "update" format just never came up.
