### ISSUE TITLE
Checkout fails

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/actions#59]
```
Run actions/checkout@v3
  with:
    fetch-depth: 0
    repository: pyiron/pyiron_vasp
    ssh-strict: true
    persist-credentials: true
    clean: true
    sparse-checkout-cone-mode: true
    fetch-tags: false
    lfs: false
    submodules: false
    set-safe-directory: true
Error: Input required and not supplied: token
``` 
For example in https://github.com/pyiron/pyiron_contrib or https://github.com/pyiron/pyiron_vasp

**Comment by liamhuber** [comment]
I won't be able to look at this until tomorrow at the absolute earliest; the first link doesn't indicate the error clearly to me, and the second link is a 404.

**Comment by jan-janssen** [comment]
All the pull requests in pyiron contrib fail https://github.com/pyiron/pyiron_contrib/pull/912 - https://github.com/pyiron/pyiron_contrib/pull/918

**Comment by jan-janssen** [comment]
The second is currently a private repository

**Comment by liamhuber** [comment]
So this seems to only be occurring for the dependabot PRs (possibly for other non-member fork PRs, but at least dependabot is the thing that's causing trouble), there's no trouble on my own PRs.

In addition to the token failure, UpdateDependabotPR / pyiron / dependabot (pull_request_target): Run pyiron/actions/update-env-files@main is failing with

```
Traceback (most recent call last):
  File "/home/runner/work/_actions/pyiron/actions/main/update-env-files/../.support/update_environment.py", line 116, in <module>
    raise ValueError(f"Title of a dependabot PR 'Bump <package> from <version> to <version>' expected, "
ValueError: Title of a dependabot PR 'Bump <package> from <version> to <version>' expected, but got Bump pyiron-base from 0.6.8 to 0.6.9 .ci_support/environment.yml /home/runner/work/_actions/pyiron/actions/main/update-env-files/../.support/pypi_vs_conda_names.json
Error: Process completed with exit code 1.
```

Which I guess is related to #56. Could that failure be causing the other tests to break?

**Comment by liamhuber** [comment]
Ok, indeed, check [here](https://github.com/pyiron/pyiron_workflow/pull/69) -- the dependabot commit has _always_ been failing the CI with such a message! It's just that after that, the centralized CI makes another commit propagating the dependabot changes to other files, and runner has all the necessary secrets!

**Comment by liamhuber** [comment]
Indeed, this is just the new issue #61 letting us once again see the known issue #44

**Comment by liamhuber** [comment]
Ah, ok, not quite just those two as dependabot should be getting extra power from `on: pull_request_target`. Let me see if that is (a) real and not just me failing to notice it was the runner commits that were actually working, and (b) different enough from #44 to warrant reopening this...

**Comment by liamhuber** [comment]
Ok, so the fork commit from dependabot itself fails the push-to-main CI, but it safely triggers pyiron runner to commit other updates and _these_ have the power to run the push-to-main CI. So #44 is still interesting for non-dependabot forks, but solving #61 really is the heart of this problem.
