### ISSUE TITLE
[Enhancement] Run code in docstrings as part of the CI

### ISSUE THREAD

**Issue by mbruns91** [pyiron/actions#60]
Corresponding to the discussion from the meeting today:

Run example-code snippets containined in docstrings as part of the CI.

**Comment by mbruns91** [comment]
References:
https://github.com/pyiron/pyiron_base/blob/049f296585c85494d20cc37a3a70bffd022a5576/tests/generic/test_datacontainer.py#L26

https://github.com/pyiron/pyiron_base/blob/049f296585c85494d20cc37a3a70bffd022a5576/pyiron_base/_tests.py#L70

**Comment by liamhuber** [comment]
This gets handled by the regular unit tests when downstream repos include doctest in their unit tests, [e.g.](https://github.com/pyiron/pyiron_workflow/blob/7bd7c3ebcee3c8a982e494a8516bf65b3cb908a3/tests/unit/test_docs.py)
