### ISSUE TITLE
Optional codacy/coverage?

### ISSUE THREAD

**Issue by pmrv** [pyiron/actions#81]
Is it possible to configure the actions to skip codacy/coverage? They are not setup for pyiron_potentialfit and won't get to it soon, so I'd rather skip them and not have the red crosses on all my PRs.

**Comment by liamhuber** [comment]
Yep, super possible. The idea is to hide various steps of the reusable workflow behind a feature flag. This is already an example of this pattern for [adding the test directory to the pythonpath](https://github.com/pyiron/actions/blob/949d289e94232df4feb8f77c6a8162338b68c015/.github/workflows/push-pull-main.yml#L159), but I guess here the new flag would default to `true` for backwards compatibility

**Comment by liamhuber** [comment]
In general I would like to follow this feature flag pattern for all cases where an action is nested (either inside actions or in a reusable workflow), the only thing holding me back is not having had time to do it.
